// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileInfo(arg1:string):Promise<{[key: string]: any}>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;
