// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearState() {
  return window['go']['main']['App']['ClearState']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadImageFile(arg1) {
  return window['go']['main']['App']['ReadImageFile'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
