// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nostr} from '../models';

export function AddRelay(arg1:string):Promise<void>;

export function ConnectRelay(arg1:string):Promise<void>;

export function GetSavedRelays():Promise<Array<string>>;

export function LoadRelays():Promise<void>;

export function RemoveRelay(arg1:string):Promise<void>;

export function SaveRelays():Promise<void>;

export function SendNote(arg1:string,arg2:string):Promise<string>;

export function SubscribeToRelay(arg1:Array<{[key: string]: any}>):Promise<Array<nostr.Event>>;
