// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRelay(arg1) {
  return window['go']['main']['RelayHandler']['AddRelay'](arg1);
}

export function ConnectRelay(arg1) {
  return window['go']['main']['RelayHandler']['ConnectRelay'](arg1);
}

export function GetSavedRelays() {
  return window['go']['main']['RelayHandler']['GetSavedRelays']();
}

export function LoadRelays() {
  return window['go']['main']['RelayHandler']['LoadRelays']();
}

export function RemoveRelay(arg1) {
  return window['go']['main']['RelayHandler']['RemoveRelay'](arg1);
}

export function SaveRelays() {
  return window['go']['main']['RelayHandler']['SaveRelays']();
}

export function SendNote(arg1, arg2) {
  return window['go']['main']['RelayHandler']['SendNote'](arg1, arg2);
}

export function SubscribeToRelay(arg1) {
  return window['go']['main']['RelayHandler']['SubscribeToRelay'](arg1);
}
